version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pattern-eb-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jocwjsmzkox6"
s3_prefix = "pattern-eb-lambda"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

